# Generated by Django 2.2.6 on 2019-10-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(blank=True, max_length=200, null=True)),
                ('line', models.CharField(blank=True, max_length=200, null=True)),
                ('process', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'workpiece',
                'managed': False,
            },
        ),
    ]
